# This is a basic workflow to help you get started with Actions

name: Staging

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04 #orai-self-hosted #self-hosted #ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copy env
        run: cp .env.example .env

      - name: Build Production
        run: npm run build
        env:
          CI: false
      # Deploy master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:oraiswap-staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # - name: Set firebase project alias
      #   run: |
      #     yarn firebase use default --token ${{ secrets.FIREBASE_TOKEN }}
      #     yarn firebase target:apply hosting oraiswap-staging oraiswap-staging --token ${{ secrets.FIREBASE_TOKEN }}
      #     yarn firebase deploy --only hosting:oraiswap-staging --token ${{ secrets.FIREBASE_TOKEN }} -m "${{ github.event.head_commit.message }}"
